dist: bionic
language: generic

addons:
  apt:
    update: true

install:
  - sudo apt-get -y install pandoc
        texlive-latex-extra
        texlive-latex-recommended
        texlive-xetex

script:
        - make build install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: pages
  target_branch: master
  local_dir: pages_dir

