dist: bionic
language: generic

addons:
  apt:
    update: true

install:
  - sudo apt-get -y install pandoc
        texlive-base lmodern 
        texlive-xetex
        texlive-luatex
        texlive-latex-extra
        texlive-latex-recommended
        texlive-fonts-recommended
  - nvm install v12.16.1
  - git submodule update
  - cd gatsby-starter-hello-world && npm install gatsby gatsby-cli react react-dom

script:
        - make build install

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: pages
  target_branch: master
  local_dir: pages

