before_install:
  - sudo apt-get -y install pandoc
        texlive-latex-extra
        texlive-latex-recommended
        texlive-xetex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: pages
  target_branch: master
  local_dir: pages_dir

